modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/YouAreHere/issues"
license="MIT"

[[mods]]
modId="youarehere"
version="${file.jarVersion}"
displayName="You Are Here"
displayURL="https://www.curseforge.com/minecraft/mc-mods/you-are-here"
authors="Mrbysco"
description='''
Tells you where you are.
'''
credits="Darkosto for the idea"
[[dependencies.youarehere]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.youarehere]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"